modLoader = "javafml"
loaderVersion = "[31,)"
license = "https://github.com/teamhollow/readyyourshovels/blob/HEAD/LICENSE"

[[mods]]
  modId = "readyyourshovels"
  displayName = "Ready Your Shovels"
  description='''
    This mod adds a whole new level to the underground, literally! Explore dirt caves filled with new mobs, blocks, and more! Dirt has never been so fun.
  '''
  authors = "Team Hollow"
  logoFile="pack.png"
  
  version = "${file.jarVersion}"
  updateJSONURL="https://teamhollow.net/data/update/readyyourshovels.json"
  
  displayURL="https://readyyourshovels.teamhollow.net"
  issueTrackerURL = "https://github.com/teamhollow/readyyourshovels/issues"
  
  [[ dependencies.readyyourshovels ]]
  modId="forge"
  mandatory=true
  versionRange="[31.0,)"
  ordering="NONE"
  side="BOTH"
  [[ dependencies.readyyourshovels ]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16,)"
  ordering="NONE"
  side="BOTH"
